import type { Metadata } from "next";

import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Footer } from "@/components/Footer";
import { exo2, inter, sometypemono, sono, spacegrotesk } from "@/lib/fonts";
import Cursor from "@/components/Cursor";
import CMDBar from "@/components/CMDBar";
import { KBarProviderWrapper } from "@/components/KBarProvider";
import { MobileNav } from "@/components/MobileNavbar";

export const metadata: Metadata = {
  title: "sahiwl",
  description: "Generated by sahiwl",
  icons: {
    icon: "/Website/app/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //removed suppressHydrationWarning={true} in html tag
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={`${sometypemono.variable} ${inter.variable} ${exo2.variable} ${sono.variable} ${spacegrotesk.variable} scroll-smooth`}
    >
      <body className="font-sometypemono dark:bg-zinc-900 bg- bg-[#eae5db]">
        <KBarProviderWrapper>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >
              <CMDBar actions={[]} />
            <main className="overflow-hidden">
              <Navbar />
              <MobileNav/>  
              <Cursor />
              {children}
              <Footer />
            </main>
          </ThemeProvider>
            </KBarProviderWrapper>
      </body>
    </html>
  );
}
