import type { Metadata } from "next";
import { Exo_2, Inter, Sometype_Mono, Space_Grotesk} from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-Inter" });
const spacegrotesk = Space_Grotesk({
subsets: ["latin"],
variable: "--font-spacegrotesk",
display: "swap"
})

const exo2 = Exo_2({
  subsets: ["latin"],
variable: "--font-exo2",
display: "swap"
})
const sometypemono = Sometype_Mono({
  subsets:["latin"],
  style: 'normal',
  display: "swap",
  variable: "--font-sometypemono"
})
// const sono = Sono({
//   subsets: ["latin"],
//   variable: "--font-sono",
//   display: "swap"
// })

export const metadata: Metadata = {
  title: "Website",
  description: "Generated by sahiwl",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    //removed suppressHydrationWarning={true} in html tag
    <html lang="en" suppressHydrationWarning={true} className={`${sometypemono.variable}`}>       
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="overflow-hidden min-h-[100vh] dark:bg-[#18181b] font-sometypemono bg-white-200">
          <Navbar/>
          {children}
          <Footer />
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
